
// Utility to handle Telegram WebApp interactions safely

// Enhance the Window interface for TypeScript
declare global {
  interface Window {
    Telegram?: {
      WebApp: any; // Using `any` for simplicity, but could be strongly typed
    };
  }
}

export const tg = window.Telegram?.WebApp;

export const initTelegramApp = () => {
  if (!tg) return;
  
  // Basic Setup
  tg.ready();
  tg.expand();
  
  // Theming & Window Control
  try {
    tg.setHeaderColor('#000000');
    tg.setBackgroundColor('#000000');
    if (tg.enableClosingConfirmation) {
        tg.enableClosingConfirmation();
    }
    // Hide default Telegram UI buttons for a cleaner fullscreen experience
    if (tg.BackButton.isVisible) {
        tg.BackButton.hide();
    }
    if (tg.MainButton.isVisible) {
        tg.MainButton.hide();
    }
  } catch (e) {
    console.warn('Telegram styling or button control not supported in this version');
  }

  // Prevent vertical swipes closing the app (if supported)
  if (tg.isVerticalSwipesEnabled) {
      // Logic if needed in future API versions
  }
};

export const hapticFeedback = (style: 'light' | 'medium' | 'heavy' | 'rigid' | 'soft') => {
  if (tg?.HapticFeedback) {
    tg.HapticFeedback.impactOccurred(style);
  } else if (navigator.vibrate) {
    // Fallback for browser testing
    navigator.vibrate(style === 'heavy' ? 50 : 20);
  }
};

export const hapticNotification = (type: 'error' | 'success' | 'warning') => {
  if (tg?.HapticFeedback) {
    tg.HapticFeedback.notificationOccurred(type);
  }
};

export const hapticSelection = () => {
  if (tg?.HapticFeedback) {
    tg.HapticFeedback.selectionChanged();
  }
};

export const getTelegramUser = () => {
  return tg?.initDataUnsafe?.user || null;
};

export const getTelegramInitData = () => {
  return tg?.initData || '';
};

/**
 * NEW: Handles instant Telegram Stars payments via openInvoice.
 * @param price - The number of stars for the invoice.
 * @returns A promise that resolves to true if payment is successful, false otherwise.
 */
export const processStarPayment = (price: number): Promise<boolean> => {
  return new Promise((resolve) => {
    // Check if the Telegram WebApp API is available
    if (tg && tg.openInvoice) {
      // In a real application, this link must be generated by your backend
      // with a unique payload to prevent replay attacks.
      // For this simulation, we'll use a placeholder.
      const invoiceLink = `https://t.me/invoice/dummy-stars?c=XTR&p=dummy_payload_for_${price}_stars&a=${price}`;

      // The callback function receives the status of the invoice.
      const onInvoiceClosed = (status: 'paid' | 'cancelled' | 'failed' | 'pending') => {
        if (status === 'paid') {
          hapticNotification('success');
          resolve(true); // Payment was successful
        } else {
          hapticNotification('error');
          resolve(false); // Payment was cancelled or failed
        }
      };
      
      tg.openInvoice(invoiceLink, onInvoiceClosed);

    } else {
      // Simulation for local development in a standard browser
      console.warn('[SIMULATION] Telegram openInvoice not available. Using confirm dialog.');
      
      const isConfirmed = window.confirm(`[DEV] Pay ${price} Stars?`);

      if (isConfirmed) {
        console.log('[SIMULATION] Payment confirmed.');
        resolve(true);
      } else {
        console.log('[SIMULATION] Payment cancelled.');
        resolve(false);
      }
    }
  });
};
